n<-1000
(rollno <- 1:n)
data.frame(rollno)
(sname=paste('Student',1:n,Sep=''))
require(caTools)
(gender=sample(x=c('M','F'),1000,replace=TRUE,prob=c(0.35,0.65)))
prop.table(table(gender))
gender = sample.split(x=c('M','F'), SplitRatio = .65) 
(age=runif(n,min=20,max=30))
  age <- round(age,0)
  age
(marks1=rnorm(n,mean=65,sd=10))
  (marks2=rnorm(n,mean=70,sd=8))
  nrows(marks1)
(passfail=sample(x=c('Pass','Fail'),n,replace=TRUE,prob=c(0.65,0.35)))
  table(passfail)
  dataiitb=data.frame(rollno,sname,gender,age,marks1,marks2,passfail)
dataiitb
dim(dataiitb)
summary(dataiitb)
write.csv(dataiitb,'./data/dataiitb.csv')
head(dataiitb)
summary(dataiitb)
str(dataiitb)
class(dataiitb)
nrow(dataiitb)
read.csv('./data/dataiitb.csv')
data2=read.csv('https://raw.githubusercontent.com/DivyaPattisapu/Learning_R/master/data/dataiitb.csv')
library(dplyr)
data2 %>% group_by(gender,passfail) %>% 
  summarise(meanM1=mean(marks1),meanM2=mean(marks2))
data2 %>% group_by(gender,passfail) %>% 
  summarise(meanM1=mean(marks1),minA=min(age),sda=sd(age)) %>% arrange(gender,desc(sda))
fit2=glm(passfail)